https://eenymeeniminimo.notion.site/20220503_EDA-baa8813ed1c4401a97697f47806b5bcd

EDA상세내역 링크 참조

In [1]:
import pandas as pd
import numpy as np

In [2]:
sg_df = pd.read_csv('./data/서울시 우리마을가게 상권분석서비스(상권영역).csv', encoding='cp949')

In [3]:
sg_df.head()

기준_년월_코드 상권_구분_코드 상권_구분_코드_명    상권_코드      상권_코드_명  엑스좌표_값  와이좌표_값  시군구_코드  \
0    202112        A       골목상권  2110753  시흥동 은행나무사거리  191934  438813   11545   
1    202112        A       골목상권  2110427   노원 을지대학교병원  206265  459431   11350   
2    202112        A       골목상권  2110755     동일여자고등학교  192300  439070   11545   
3    202112        A       골목상권  2110739   시흥3동 우편취급국  191289  438014   11545   
4    202112        A       골목상권  2111017     송파나루역 3번  210222  445516   11710   

     행정동_코드  형태정보  
0  11545710   NaN  
1  11350611   NaN  
2  11545680   NaN  
3  11545690   NaN  
4  11710562   NaN

In [5]:
sg_chk_df =sg_df.groupby( ['기준_년월_코드', '상권_구분_코드', '상권_코드'])['상권_코드_명'].count().reset_index()

In [7]:
sg_chk_df['상권_코드_명'].sum()

1671

In [8]:
sg_chk_df.shape

(1671, 4)

In [9]:
sg_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1671 entries, 0 to 1670
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   기준_년월_코드    1671 non-null   int64  
 1   상권_구분_코드    1671 non-null   object 
 2   상권_구분_코드_명  1671 non-null   object 
 3   상권_코드       1671 non-null   int64  
 4   상권_코드_명     1671 non-null   object 
 5   엑스좌표_값      1671 non-null   int64  
 6   와이좌표_값      1671 non-null   int64  
 7   시군구_코드      1671 non-null   int64  
 8   행정동_코드      1671 non-null   int64  
 9   형태정보        0 non-null      float64
dtypes: float64(1), int64(6), object(3)
memory usage: 130.7+ KB


In [10]:
sg_df['기준_년월_코드'].unique()

array([202112])

In [11]:
sg_df['상권_구분_코드'].unique()

array(['A', 'D', 'R', 'U'], dtype=object)

In [12]:
np.unique(list(sg_df.loc[sg_df['상권_구분_코드']=='A', '상권_코드']//1000))

array([2110, 2111])

In [13]:
len(sg_df.loc[sg_df['상권_구분_코드']=='A', '상권_코드'].unique())

1090

In [14]:
sg_df.loc[sg_df['상권_구분_코드']=='A', '상권_코드']
# .str.slice(0, 4)

0       2110753
1       2110427
2       2110755
3       2110739
4       2111017
         ...   
1085    2110881
1086    2110874
1087    2110887
1088    2110944
1089    2110870
Name: 상권_코드, Length: 1090, dtype: int64

In [15]:
sg_df['엑스좌표_값'].min()

182574

In [16]:
sg_df['엑스좌표_값'].max()

215356

In [17]:
sg_df['시군구_코드']

0       11545
1       11350
2       11545
3       11545
4       11710
        ...  
1666    11140
1667    11110
1668    11710
1669    11680
1670    11170
Name: 시군구_코드, Length: 1671, dtype: int64

In [18]:
sg_df[sg_df['시군구_코드']==sg_df['행정동_코드']//1000]

기준_년월_코드 상권_구분_코드 상권_구분_코드_명    상권_코드       상권_코드_명  엑스좌표_값  와이좌표_값  \
0       202112        A       골목상권  2110753   시흥동 은행나무사거리  191934  438813   
1       202112        A       골목상권  2110427    노원 을지대학교병원  206265  459431   
2       202112        A       골목상권  2110755      동일여자고등학교  192300  439070   
3       202112        A       골목상권  2110739    시흥3동 우편취급국  191289  438014   
4       202112        A       골목상권  2111017      송파나루역 3번  210222  445516   
...        ...      ...        ...      ...           ...     ...     ...   
1666    202112        U       관광특구  1001493  동대문패션타운 관광특구  200974  451975   
1667    202112        U       관광특구  1001494    종로?청계 관광특구  199768  452273   
1668    202112        U       관광특구  1001495       잠실 관광특구  210191  446339   
1669    202112        U       관광특구  1001496   강남 마이스 관광특구  205310  445727   
1670    202112        U       관광특구  1001491      이태원 관광특구  199503  448326   

      시군구_코드    행정동_코드  형태정보  
0      11545  11545710   NaN  
1      11350  11350611   NaN  
2      11545  11545680   NaN  
3      11545  11545690   NaN  
4      11710  11710562   NaN  
...      ...       ...   ...  
1666   11140  11140590   NaN  
1667   11110  11110615   NaN  
1668   11710  11710566   NaN  
1669   11680  11680580   NaN  
1670   11170  11170650   NaN  

[1671 rows x 10 columns]

In [19]:
sg_df['형태정보'].unique()

array([nan])

In [20]:
jg_df = pd.read_csv('./data/서울시 우리마을가게 상권분석서비스(상권-집객시설).csv', encoding='cp949')

In [21]:
jg_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31722 entries, 0 to 31721
Data columns (total 26 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   기준_년_코드     31722 non-null  int64  
 1   기준_분기_코드    31722 non-null  int64  
 2   상권_구분_코드    31722 non-null  object 
 3   상권_구분_코드_명  31722 non-null  object 
 4   상권_코드       31722 non-null  int64  
 5   상권_코드_명     31722 non-null  object 
 6   집객시설_수      31722 non-null  int64  
 7   관공서_수       12080 non-null  float64
 8   은행_수        10651 non-null  float64
 9   종합병원_수      511 non-null    float64
 10  일반_병원_수     3435 non-null   float64
 11  약국_수        20900 non-null  float64
 12  유치원_수       4385 non-null   float64
 13  초등학교_수      163 non-null    float64
 14  중학교_수       35 non-null     float64
 15  고등학교_수      104 non-null    float64
 16  대학교_수       715 non-null    float64
 17  백화점_수       292 non-null    float64
 18  슈퍼마켓_수      2830 non-null   float64
 19  극장_수        2542 non-null

In [22]:
jg_df['기준_년_코드'].unique()

array([2021, 2020, 2019, 2018, 2017])

In [23]:
jg_df['기준_분기_코드'].unique()

array([4, 3, 2, 1])

In [24]:
jg_df['상권_구분_코드'].unique()

array(['A', 'R', 'D', 'U'], dtype=object)

In [25]:
jg_df['상권_구분_코드_명'].unique()

array(['골목상권', '전통시장', '발달상권', '관광특구'], dtype=object)

In [26]:
jg_df['상권_코드'].unique()

array([2110939, 2110148, 2130039, ..., 2111045, 2130247, 2110987])

In [27]:
jg_df.head()

기준_년_코드  기준_분기_코드 상권_구분_코드 상권_구분_코드_명    상권_코드                상권_코드_명  \
0     2021         4        A       골목상권  2110939         양재역 8번(양재동우체국)   
1     2021         4        A       골목상권  2110148             어린이대공원역 3번   
2     2021         4        R       전통시장  2130039             청계6가 지하도상가   
3     2021         4        R       전통시장  2130028  을지입구지하상가(을지로지하보도쇼핑센터)   
4     2021         4        A       골목상권  2110231                    장안교   

   집객시설_수  관공서_수  은행_수  종합병원_수  ...  대학교_수  백화점_수  슈퍼마켓_수  극장_수  숙박_시설_수  \
0      23    NaN   NaN     NaN  ...    1.0    NaN     NaN   NaN      NaN   
1       1    NaN   NaN     NaN  ...    NaN    NaN     NaN   NaN      NaN   
2       1    NaN   NaN     NaN  ...    NaN    NaN     NaN   NaN      NaN   
3       1    NaN   NaN     NaN  ...    NaN    NaN     NaN   NaN      NaN   
4       2    NaN   NaN     NaN  ...    NaN    NaN     NaN   NaN      NaN   

   공항_수  철도_역_수  버스_터미널_수  지하철_역_수  버스_정거장_수  
0   NaN     NaN       NaN      NaN       5.0  
1   NaN     NaN       NaN      NaN       NaN  
2   NaN     NaN       NaN      NaN       NaN  
3   NaN     NaN       NaN      1.0       NaN  
4   NaN     NaN       NaN      NaN       NaN  

[5 rows x 26 columns]

In [28]:
jg_chk_df =jg_df.groupby( ['기준_년_코드', '기준_분기_코드', '상권_코드'])['상권_구분_코드'].count().reset_index()

In [29]:
jg_chk_df['상권_구분_코드'].sum()

31722

In [30]:
jg_chk_df.shape

(31722, 4)

In [32]:
jg_df.columns

Index(['기준_년_코드', '기준_분기_코드', '상권_구분_코드', '상권_구분_코드_명', '상권_코드', '상권_코드_명',
       '집객시설_수', '관공서_수', '은행_수', '종합병원_수', '일반_병원_수', '약국_수', '유치원_수',
       '초등학교_수', '중학교_수', '고등학교_수', '대학교_수', '백화점_수', '슈퍼마켓_수', '극장_수',
       '숙박_시설_수', '공항_수', '철도_역_수', '버스_터미널_수', '지하철_역_수', '버스_정거장_수'],
      dtype='object')

In [33]:
jp_df = pd.read_csv('./data/서울시 우리마을가게 상권분석서비스(상권-점포).csv', encoding='cp949')

In [34]:
jp_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 598403 entries, 0 to 598402
Data columns (total 15 columns):
 #   Column       Non-Null Count   Dtype 
---  ------       --------------   ----- 
 0   기준_년_코드      598403 non-null  int64 
 1   기준_분기_코드     598403 non-null  int64 
 2   상권_구분_코드     598403 non-null  object
 3   상권_구분_코드_명   598403 non-null  object
 4   상권_코드        598403 non-null  int64 
 5   상권_코드_명      598403 non-null  object
 6   서비스_업종_코드    598403 non-null  object
 7   서비스_업종_코드_명  598403 non-null  object
 8   점포_수         598403 non-null  int64 
 9   유사_업종_점포_수   598403 non-null  int64 
 10  개업_율         598403 non-null  int64 
 11  개업_점포_수      598403 non-null  int64 
 12  폐업_률         598403 non-null  int64 
 13  폐업_점포_수      598403 non-null  int64 
 14  프랜차이즈_점포_수   598403 non-null  int64 
dtypes: int64(10), object(5)
memory usage: 68.5+ MB


In [38]:
jp_chk_df =jp_df.groupby( ['기준_년_코드', '기준_분기_코드', '상권_구분_코드', '상권_코드', '서비스_업종_코드'])['점포_수'].count().reset_index()

In [41]:
jp_chk_df['점포_수'].sum()

598403

In [42]:
jp_chk_df.shape

(598403, 6)

In [44]:
jp_df['기준_년_코드'].unique()

array([2021, 2020])

In [45]:
jp_df['기준_분기_코드'].unique()

array([4, 3, 2, 1])

In [48]:
len(jp_df['서비스_업종_코드'].unique())

100

In [47]:
jp_df['서비스_업종_코드_명'].unique()

array(['전자상거래업', '주유소', '예술품', '자동차부품', '조명용품', '인테리어', '악기', '철물점',
       '가전제품', '가구', '애완동물', '화초', '섬유제품', '완구', '운동/경기용품', '미용재료', '화장품',
       '문구', '서적', '의료기기', '의약품', '시계및귀금속', '안경', '가방', '신발', '유아의류',
       '일반의류', '반찬가게', '청과상', '육류판매', '미곡판매', '주류도매', '핸드폰', '컴퓨터및주변장치판매',
       '편의점', '슈퍼마켓', '여행사', '건축물청소', '통번역서비스', '사진관', '부동산중개업', '세탁소',
       '피부관리실', '네일숍', '미용실', '자동차미용', '스포츠클럽', 'PC방', '세무사사무소',
       '기타법무서비스', '법무사사무소', '변호사사무소', '치과의원', '일반의원', '외국어학원', '일반교습학원',
       '커피-음료', '분식전문점', '패스트푸드점', '제과점', '양식음식점', '일식음식점', '중식음식점',
       '한식음식점', '재생용품 판매점', '중고차판매', '자전거 및 기타운송장비', '수산물판매', '의류임대',
       '비디오/서적임대', '녹음실', 'DVD방', '노래방', '고시원', '여관', '가전제품수리', '자동차수리',
       '통신기기수리', '복권방', '기타오락장', '볼링장', '골프연습장', '당구장', '회계사사무소',
       '변리사사무소', '동물병원', '한의원', '스포츠 강습', '컴퓨터학원', '예술학원', '호프-간이주점',
       '치킨전문점', '한복점', '가정용품임대', '독서실', '게스트하우스', '모터사이클수리', '전자게임장',
       '모터사이클및부품', '중고가구'], dtype=object)

In [49]:
jp_df.columns

Index(['기준_년_코드', '기준_분기_코드', '상권_구분_코드', '상권_구분_코드_명', '상권_코드', '상권_코드_명',
       '서비스_업종_코드', '서비스_업종_코드_명', '점포_수', '유사_업종_점포_수', '개업_율', '개업_점포_수',
       '폐업_률', '폐업_점포_수', '프랜차이즈_점포_수'],
      dtype='object')